# 1.0 Reading in File  --------------

In [1166]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [1167]:
import pandas as pd

file_path = '/content/drive/MyDrive/listings.csv'
df = pd.read_csv(file_path)
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3176,https://www.airbnb.com/rooms/3176,20260626225638,2026-07-03,previous scrape,Fabulous Flat in great Location,This beautiful first floor apartment is situa...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,3718,...,4.70,4.92,4.61,First name and Last name: Nicolas Krotz <br/> ...,NaN,1,1,0,0,0.72
1,9991,https://www.airbnb.com/rooms/9991,20260626225638,2026-06-27,city scrape,Geourgeous flat - outstanding views,4 bedroom with very large windows and outstand...,NaN,https://a0.muscache.com/pictures/42799131/59c8...,33852,...,5.00,4.86,4.86,03/Z/RA/003410-18,NaN,1,1,0,0,0.05
2,14325,https://www.airbnb.com/rooms/14325,20260626225638,2026-07-03,previous scrape,Studio Apartment in Prenzlauer Berg,The apartment is located on the upper second f...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,55531,...,4.85,4.60,4.45,NaN,NaN,2,2,0,0,0.13
3,17904,https://www.airbnb.com/rooms/17904,20260626225638,2026-07-03,previous scrape,Beautiful Kreuzberg studio - 3 months minimum,- bright studio with scenic view on a river - ...,NaN,https://a0.muscache.com/pictures/d9a6f8be-54b9...,68997,...,4.92,4.88,4.65,NaN,NaN,1,1,0,0,1.49
4,20858,https://www.airbnb.com/rooms/20858,20260626225638,2026-06-27,city scrape,Designer Loft in Berlin Mitte,Bright and sunny condo with two balconies in a...,NaN,https://a0.muscache.com/pictures/108232/205b19...,71331,...,4.55,4.92,4.40,03/Z/RA/009767-24,NaN,1,1,0,0,0.87

# 1.1  Brief Overview --------------

In [1168]:
df.describe()

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,1.277600e+04,1.277600e+04,0.0,1.277600e+04,1.276000e+04,0.0,12760.000000,12760.000000,12760.000000,12760.000000,...,10201.000000,10203.000000,10201.000000,10201.000000,0.0,12776.000000,12776.000000,12776.000000,12776.000000,10203.000000
mean,6.144901e+17,2.026063e+13,NaN,3.696258e+15,1.471278e+18,NaN,8.222179,5.758777,6.454389,5.645925,...,4.832955,4.830695,4.768241,4.651415,NaN,14.433312,13.194427,1.034909,0.141124,1.340282
std,6.324319e+17,3.910309e+00,NaN,7.887474e+16,2.688485e+16,NaN,4.146422,3.519559,4.148220,3.482203,...,0.313080,0.341911,0.307369,0.393563,NaN,45.244762,45.219126,2.773292,1.527326,1.957176
min,3.176000e+03,2.026063e+13,NaN,2.217000e+03,1.462506e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,2.497952e+07,2.026063e+13,NaN,1.754369e+07,1.462887e+18,NaN,5.000000,3.000000,3.000000,3.000000,...,4.800000,4.800000,4.690000,4.540000,NaN,1.000000,0.000000,0.000000,0.000000,0.140000
50%,6.267416e+17,2.026063e+13,NaN,1.015032e+08,1.466838e+18,NaN,9.000000,6.000000,7.000000,6.000000,...,4.920000,4.930000,4.850000,4.730000,NaN,1.000000,1.000000,0.000000,0.000000,0.640000
75%,1.211491e+18,2.026063e+13,NaN,4.020121e+08,1.469768e+18,NaN,11.000000,9.000000,10.000000,9.000000,...,5.000000,5.000000,4.970000,4.880000,NaN,5.000000,3.000000,1.000000,0.000000,1.940000
max,1.715913e+18,2.026063e+13,NaN,1.711581e+18,1.714641e+18,NaN,17.000000,11.000000,15.000000,11.000000,...,5.000000,5.000000,5.000000,5.000000,NaN,261.000000,261.000000,25.000000,23.000000,45.120000

### There are too many columns in the dataset to explore within reason.
Therefore, I will explore the data and remove unusable or unecessary columns

In [1169]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_profile_id', 'host_profile_url', 'host_name',
       'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [1170]:
na_prop = df.isna().mean()
na_cols = na_prop[na_prop >= 0.75]
na_cols

neighborhood_overview        1.0
host_since                   1.0
host_response_time           1.0
host_response_rate           1.0
host_acceptance_rate         1.0
host_thumbnail_url           1.0
host_neighbourhood           1.0
host_total_listings_count    1.0
host_verifications           1.0
neighbourhood                1.0
calendar_updated             1.0
instant_bookable             1.0
dtype: float64

In [1171]:
df = df.drop(na_cols.index, axis=1)

# 1.2 Host Table Cleaning --------------

The listings table has host that can be seperated into its own table.
Since the relationship from listings to hosts is many to one, the host data appears many times within the listings table.
 However, after removing these duplicate rows, we find there are still duplicate ids in the table.

In [1172]:
host_cols = ['host_id',
       'host_url', 'host_profile_id', 'host_profile_url', 'host_name', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
       'host_location', 'host_about', 'host_is_superhost', 'host_picture_url',
       'host_listings_count',
      'host_has_profile_pic', 'host_identity_verified', 'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms']
df_host = df[host_cols]

df_host = df_host.drop_duplicates()
df_host["host_id"].value_counts()

host_id
560640615    2
695648086    2
198110578    2
706243170    2
689937375    2
            ..
113265170    1
150545454    1
1219287      1
75787504     1
23211273     1
Name: count, Length: 8182, dtype: int64

Upon further inspection, it appears that remaining duplicate ids are due to  values for the 'host_profile_url' column being present in one instance but not the other.

In [1173]:
duplicate_hosts = df_host["host_id"].value_counts()[df_host["host_id"].value_counts() > 1]
duplicate_ids = duplicate_hosts.index

df_host[df_host["host_id"].isin(duplicate_ids)].sort_values(by='host_id')

,host_id,host_url,host_profile_id,host_profile_url,host_name,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_is_superhost,host_picture_url,host_listings_count,host_has_profile_pic,host_identity_verified,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
5156,4011048,https://www.airbnb.com/users/show/4011048,1.462533e+18,https://www.airbnb.com/users/profile/146253307...,Yumi,13.0,8.0,6.0,0.0,"Berlin, Germany",Hi friends! I am in Berlin since 2006 and wor...,t,https://a0.muscache.com/im/pictures/user/901de...,3.0,t,t,3,1,2,0
5182,4011048,https://www.airbnb.com/users/show/4011048,1.462533e+18,NaN,Yumi,13.0,8.0,6.0,0.0,"Berlin, Germany",Hi friends! I am in Berlin since 2006 and wor...,t,https://a0.muscache.com/im/pictures/user/901de...,3.0,t,t,3,1,2,0
5834,198110578,https://www.airbnb.com/users/show/198110578,1.469032e+18,https://www.airbnb.com/users/profile/146903217...,Sarah,8.0,0.0,5.0,8.0,"Berlin, Germany",NaN,f,https://a0.muscache.com/im/pictures/user/f77d6...,2.0,t,t,2,0,2,0
6554,198110578,https://www.airbnb.com/users/show/198110578,1.469032e+18,NaN,Sarah,8.0,0.0,5.0,8.0,"Berlin, Germany",NaN,f,https://a0.muscache.com/im/pictures/user/f77d6...,2.0,t,t,2,0,2,0
8335,547505934,https://www.airbnb.com/users/show/547505934,1.470450e+18,NaN,Hotel AMO By AMANO,2.0,7.0,2.0,7.0,NaN,"Welcome to Hotel AMO, where Berlin charm meets...",f,https://a0.muscache.com/im/pictures/user/91f0a...,4.0,t,t,3,0,3,0
10952,547505934,https://www.airbnb.com/users/show/547505934,1.470450e+18,https://www.airbnb.com/users/profile/147044975...,Hotel AMO By AMANO,2.0,7.0,2.0,7.0,NaN,"Welcome to Hotel AMO, where Berlin charm meets...",f,https://a0.muscache.com/im/pictures/user/91f0a...,4.0,t,t,3,0,3,0
8793,560640615,https://www.airbnb.com/users/show/560640615,NaN,https://www.airbnb.com/users/profile/147050472...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,0
8791,560640615,https://www.airbnb.com/users/show/560640615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,0
10660,686441652,https://www.airbnb.com/users/show/686441652,NaN,https://www.airbnb.com/users/profile/147071346...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,0
10661,686441652,https://www.airbnb.com/users/show/686441652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,0
10742,689937375,https://www.airbnb.com/users/show/689937375,NaN,https://www.airbnb.com/users/profile/147072096...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0
10741,689937375,https://www.airbnb.com/users/show/689937375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0
10754,690328181,https://www.airbnb.com/users/show/690328181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,4,0
10790,690328181,https://www.airbnb.com/users/show/690328181,NaN,https://www.airbnb.com/users/profile/147072185...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,4,0
10886,695648086,https://www.airbnb.com/users/show/695648086,1.470733e+18,NaN,"Hotel Provocateur, Part Of Sircle Collection",1.0,1.0,1.0,1.0,NaN,Hotel Provocateur Berlin is a stylish boutique...,f,https://a0.muscache.com/im/pictures/user/User/...,8.0,t,t,5,0,5,0
10887,695648086,https://www.airbnb.com/users/show/695648086,1.470733e+18,https://www.airbnb.com/users/profile/147073306...,"Hotel Provocateur, Part Of Sircle Collection",1.0,1.0,1.0,1.0,NaN,Hotel Provocateur Berlin is a stylish boutique...,f,https://a0.muscache.com/im/pictures/user/User/...,8.0,t,t,5,0,5,0
11180,706243170,https://www.airbnb.com/users/show/706243170,1.470753e+18,https://www.airbnb.com/users/profile/147075310...,The Social Hub Berlin,0.0,11.0,0.0,11.0,NaN,"Whether you're here for a week or a while, The...",t,https://a0.muscache.com/im/pictures/user/User/...,8.0,t,t,7,0,7,0
11181,706243170,https://www.airbnb.com/users/show/706243170,1.470753e+18,NaN,The Social Hub Berlin,0.0,11.0,0.0,11.0,NaN,"Whether you're here for a week or a while, The...",t,https://a0.muscache.com/im/pictures/user/User/...,8.0,t,t,7,0,7,0
11640,723284548,https://www.airbnb.com/users/show/723284548,1.528833e+18,https://www.airbnb.com/users/profile/152883302...,B&B Hotel Berlin Alexanderplatz,0.0,8.0,0.0,8.0,NaN,"Welcome to B&B Hotel Berlin Alexanderplatz, yo...",f,https://a0.muscache.com/im/pictures/user/User/...,5.0,t,t,2,0,2,0
12318,723284548,https://www.airbnb.com/users/show/723284548,1.528833e+18,NaN,B&B Hotel Berlin Alexanderplatz,0.0,8.0,0.0,8.0,NaN,"Welcome to B&B Hotel Berlin Alexanderplatz, yo...",f,https://a0.muscache.com/im/pictures/user/User/...,5.0,t,t,2,0,2,0

Since duplicate rows have are identical except for the profile url, we can drop the duplicate row without the profile url. This results in a table free of duplicate ids.

In [1174]:
drop_idx = df_host[df_host["host_id"].isin(duplicate_ids) & df_host["host_profile_url"].isna()].index
df_host = df_host.drop(index = drop_idx)

len(df_host["host_id"].value_counts()[df_host["host_id"].value_counts() > 1])

0

The host columns can be dropped from the listings table, but host_id is kept in order to maintain the relationship

In [1175]:
df_clean = df.drop([col for col in host_cols if col != "host_id"], axis=1)
df_clean.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'picture_url', 'host_id', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'reviews_per_month'],
      dtype='object')

Now that the table structure is valid, we can work on cleaning the remaining columns

In [1176]:
df_host.head()

,host_id,host_url,host_profile_id,host_profile_url,host_name,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_is_superhost,host_picture_url,host_listings_count,host_has_profile_pic,host_identity_verified,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,3718,https://www.airbnb.com/users/show/3718,1.462506e+18,https://www.airbnb.com/users/profile/146250639...,Britta,17.0,8.0,15.0,6.0,"Coledale, Australia",We love to travel ourselves a lot and prefer t...,f,https://a0.muscache.com/im/users/3718/profile_...,1.0,t,t,1,1,0,0
1,33852,https://www.airbnb.com/users/show/33852,1.462507e+18,https://www.airbnb.com/users/profile/146250721...,Philipp,16.0,10.0,12.0,0.0,"Berlin, Germany",Born in Munich - lives in and loves Berlin. Wo...,f,https://a0.muscache.com/im/users/33852/profile...,1.0,t,t,1,1,0,0
2,55531,https://www.airbnb.com/users/show/55531,1.462508e+18,https://www.airbnb.com/users/profile/146250781...,Chris Und Oliver,16.0,7.0,15.0,6.0,"Berlin, Germany","From Berlin, Germany. We love to travel!",f,https://a0.muscache.com/im/users/55531/profile...,2.0,t,t,2,2,0,0
3,68997,https://www.airbnb.com/users/show/68997,1.462508e+18,https://www.airbnb.com/users/profile/146250830...,Matthias,16.0,5.0,15.0,6.0,"Rio de Janeiro, Brazil",I am a journalist/writer. Lived in NYC for ...,t,https://a0.muscache.com/im/pictures/user/67b13...,2.0,t,t,1,1,0,0
4,71331,https://www.airbnb.com/users/show/71331,1.462508e+18,https://www.airbnb.com/users/profile/146250835...,Marc,16.0,5.0,15.0,5.0,"Hamburg, Germany","I am looking forward to your arrival, so I can...",t,https://a0.muscache.com/im/users/71331/profile...,2.0,t,t,1,1,0,0

The host profile url is redundant since it can be generated directly from the host id. Thus we will remove this column to simplify the overall table.

In [1177]:
print(len(df_host[df_host["host_url"] != "https://www.airbnb.com/users/show/" + df_host["host_id"].astype(str)]))
df_host = df_host.drop('host_url', axis=1)

0

We can apply similar logic to remove the 'host_profile_url' column. These columns are the same as far as is output, despite checks returning differences. Regardless, the url column is unlikely to be useful for exploration. Therefore, this column will be dropped too.

In [1178]:
df_host['host_profile_id'] = df_host['host_profile_id'].astype('Int64')

print("Number of differing rows: "  + str(len(
    df_host[
        (df_host["host_profile_url"] != "https://www.airbnb.com/users/profile/" + df_host["host_profile_id"].astype(str)) &
        df_host["host_profile_id"].notna()
        ])))

df_host.loc[df_host["host_profile_url"] != ("https://www.airbnb.com/users/profile/" + df_host["host_profile_id"].astype(str)),
            ["host_profile_url", "host_profile_id"]]
df_host = df_host.drop('host_profile_url', axis=1)

Number of differing rows: 8142

The name column has very few missing values and appears to be free of errors

In [1179]:
print("Number of NA values in name column: " + str(df_host["host_name"].isna().sum()))
print("Number of empty values in name column: " + str((df_host["host_name"] == "").sum()))
df_host["host_name"].head(20)

Number of NA values in name column: 7
Number of empty values in name column: 0

0                       Britta
1                      Philipp
2             Chris Und Oliver
3                     Matthias
4                         Marc
5                       Javier
6                       Ramfis
7                        Tanja
8                      Michele
9                    Christian
10                       Bernd
11                     Desiree
12                          Bn
14                        Tina
15                      Britta
16                      Marine
17                       Katja
18                     Stephan
19                   Christian
20    Alan & Kasia StayBearlin
Name: host_name, dtype: object

We can check the logic of the hosts_time_as_... columns. Since a host has to have been a user at least as long as they have been a host, we can check all rows for this condition. We can also ensure that months are between the intended range.

In [1180]:
time_as_cols = ['hosts_time_as_user_years',	'hosts_time_as_user_months',	'hosts_time_as_host_years',	'hosts_time_as_host_months']
df_host[time_as_cols] = df_host[time_as_cols].apply(lambda col: col.astype('Int64')) # converting unnecessary float cols to ints

print("Number of rows with host years > user years: " + str(len(df_host[df_host['hosts_time_as_user_years'] < df_host['hosts_time_as_host_years']])))
print(df_host.loc[df_host['hosts_time_as_user_years'] < df_host['hosts_time_as_host_years'],
                      ["hosts_time_as_user_years", "hosts_time_as_host_years"]])

print("Number of rows with host years + month > user years + month: " + str(len(df_host[
    (df_host['hosts_time_as_user_years'] == df_host['hosts_time_as_host_years']) &
    (df_host['hosts_time_as_user_months'] < df_host['hosts_time_as_host_months'])
    ])))
print(df_host.loc[(df_host['hosts_time_as_user_years'] == df_host['hosts_time_as_host_years']) &
    (df_host['hosts_time_as_user_months'] < df_host['hosts_time_as_host_months']),
                      ["hosts_time_as_user_years", "hosts_time_as_host_years"]])

#months should be between 0 and 12
print("Number of rows with user months >= 12 or < 0: " + str(len(df_host[
    (df_host['hosts_time_as_user_months'] >= 12) | (df_host['hosts_time_as_user_months'] < 0)
    ])))
print(df_host.loc[df_host['hosts_time_as_user_months'] >= 12,
                      ["hosts_time_as_user_years", "hosts_time_as_host_years"]])

print("Number of rows with host months >= 12 or < 0: " + str(len(df_host[
    (df_host['hosts_time_as_host_months'] >= 12) | (df_host['hosts_time_as_host_months'] < 0)
    ])))
print(df_host.loc[df_host['hosts_time_as_host_months'] >= 12,
                 ["hosts_time_as_user_years", "hosts_time_as_host_years"]])

Number of rows with host years > user years: 3
      hosts_time_as_user_years  hosts_time_as_host_years
114                         13                        14
4540                        14                        15
5919                        13                        14
Number of rows with host years + month > user years + month: 1
   hosts_time_as_user_years  hosts_time_as_host_years
8                        15                        15
Number of rows with user months >= 12 or < 0: 0
Empty DataFrame
Columns: [hosts_time_as_user_years, hosts_time_as_host_years]
Index: []
Number of rows with host months >= 12 or < 0: 0
Empty DataFrame
Columns: [hosts_time_as_user_years, hosts_time_as_host_years]
Index: []

The 4 rows with errors are dropped for consistency.

In [1181]:
drop_idx = df_host.loc[df_host['hosts_time_as_user_years'] < df_host['hosts_time_as_host_years'],
                      ["hosts_time_as_user_years", "hosts_time_as_host_years"]].index
df_host = df_host.drop(index = drop_idx)

drop_idx = df_host[
    (df_host['hosts_time_as_user_years'] == df_host['hosts_time_as_host_years']) &
    (df_host['hosts_time_as_user_months'] < df_host['hosts_time_as_host_months'])].index
df_host = df_host.drop(index = drop_idx)

In [1182]:
bool_cols = ['host_is_superhost',	'host_has_profile_pic',	'host_identity_verified']
df_host[bool_cols] = df_host[bool_cols].apply(lambda col: col.map({'t':True, 'f':False}))
df_host[bool_cols].head()

  host_is_superhost host_has_profile_pic host_identity_verified
0             False                 True                   True
1             False                 True                   True
2             False                 True                   True
3              True                 True                   True
4              True                 True                   True

In [1183]:
count_cols = ['host_listings_count', 'calculated_host_listings_count',	'calculated_host_listings_count_entire_homes',	'calculated_host_listings_count_private_rooms',	'calculated_host_listings_count_shared_rooms']
for col in count_cols:
  print(df_host[col].value_counts(dropna=False).head())

df_host[count_cols] = df_host[count_cols].apply(lambda col: col.astype('Int64'))

host_listings_count
1.0    6247
2.0     999
3.0     310
4.0     153
5.0     116
Name: count, dtype: int64
calculated_host_listings_count
1    6889
2     674
3     217
5      93
4      89
Name: count, dtype: int64
calculated_host_listings_count_entire_homes
1    4862
0    2568
2     342
3     134
5      63
Name: count, dtype: int64
calculated_host_listings_count_private_rooms
0    5372
1    2414
2     222
3      61
4      31
Name: count, dtype: int64
calculated_host_listings_count_shared_rooms
0     8158
1        9
3        3
2        2
10       1
Name: count, dtype: int64

In [1184]:
df_host.head()

,host_id,host_profile_id,host_name,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_is_superhost,host_picture_url,host_listings_count,host_has_profile_pic,host_identity_verified,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,3718,1462506392471524096,Britta,17,8,15,6,"Coledale, Australia",We love to travel ourselves a lot and prefer t...,False,https://a0.muscache.com/im/users/3718/profile_...,1,True,True,1,1,0,0
1,33852,1462507217953343232,Philipp,16,10,12,0,"Berlin, Germany",Born in Munich - lives in and loves Berlin. Wo...,False,https://a0.muscache.com/im/users/33852/profile...,1,True,True,1,1,0,0
2,55531,1462507816786617600,Chris Und Oliver,16,7,15,6,"Berlin, Germany","From Berlin, Germany. We love to travel!",False,https://a0.muscache.com/im/users/55531/profile...,2,True,True,2,2,0,0
3,68997,1462508300544974080,Matthias,16,5,15,6,"Rio de Janeiro, Brazil",I am a journalist/writer. Lived in NYC for ...,True,https://a0.muscache.com/im/pictures/user/67b13...,2,True,True,1,1,0,0
4,71331,1462508352290887680,Marc,16,5,15,5,"Hamburg, Germany","I am looking forward to your arrival, so I can...",True,https://a0.muscache.com/im/users/71331/profile...,2,True,True,1,1,0,0

# 1.3 Review Statistics Table Cleaning --------------

In [1185]:
review_statistics_cols = ['id', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
        'number_of_reviews_ly','first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'reviews_per_month']
df_review_statistics = df_clean[review_statistics_cols]
df_review_statistics.rename(columns={'id': 'listing_id'}, inplace=True)

#This relationship from listings to hosts is one to one. There should not be any duplicates in this table since it is one for each listing
df_review_statistics["listing_id"].value_counts()

/tmp/ipykernel_1076/3804206786.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_review_statistics.rename(columns={'id': 'listing_id'}, inplace=True)

listing_id
1715912659116099298    1
3176                   1
9991                   1
14325                  1
17904                  1
                      ..
41217                  1
37836                  1
37004                  1
34854                  1
30295                  1
Name: count, Length: 12776, dtype: int64

In [1186]:
df_review_statistics.head()

,listing_id,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,3176,150,1,0,2,2009-06-20,2025-08-09,4.63,4.67,4.52,4.65,4.70,4.92,4.61,0.72
1,9991,7,0,0,0,2015-08-09,2020-01-04,5.00,5.00,5.00,5.00,5.00,4.86,4.86,0.05
2,14325,26,0,0,0,2010-06-29,2023-11-30,4.68,5.00,4.85,4.70,4.85,4.60,4.45,0.13
3,17904,298,2,0,1,2010-02-18,2026-05-31,4.77,4.82,4.71,4.89,4.92,4.88,4.65,1.49
4,20858,145,6,1,4,2012-10-03,2026-05-29,4.49,4.61,4.65,4.51,4.55,4.92,4.40,0.87

While there are a significant amount of NA values, the remaining columns may still be relevant so these rows wont be removed. Furthermore, since there are so many of these values, removing these rows may have a negative impact on the reamining clean columns.

In [1187]:
print(len(df_review_statistics))
df_review_statistics.isna().sum()

12776

listing_id                        0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
number_of_reviews_ly              0
first_review                   2573
last_review                    2573
review_scores_rating           2573
review_scores_accuracy         2574
review_scores_cleanliness      2573
review_scores_checkin          2575
review_scores_communication    2573
review_scores_location         2575
review_scores_value            2575
reviews_per_month              2573
dtype: int64

The columns had a similar number of NA values, here we can see that except for a few rows, most of the NA instances of these columns occur in all of these columns at once.

In [1188]:
na_cols = ['first_review','last_review','review_scores_rating','review_scores_accuracy','review_scores_cleanliness',
           'review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value','reviews_per_month']
len(df_review_statistics[df_review_statistics[na_cols].isna().all(axis=1)])

2573

#1.4 Listings Table Cleaning --------------

In [1189]:
df_clean = df_clean.drop([col for col in review_statistics_cols if col != "id"], axis=1)
df_clean.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'picture_url', 'host_id', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'availability_eoy',
       'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'license'],
      dtype='object')

In [1190]:
#The dropped "neighbourhood" column is useless; it contains only NA values. Whereas "neighbourhood_cleansed" is what the column should be.
print(df_clean["neighbourhood_cleansed"].value_counts(dropna=False).head())

neighbourhood_cleansed
Alexanderplatz              884
Frankfurter Allee Süd FK    675
Tempelhofer Vorstadt        568
Brunnenstr. Süd             514
Prenzlauer Berg Südwest     378
Name: count, dtype: int64

In [1191]:
#The dropped 'neighborhood_overview' column is also useless and contains no data. Whereas the 'neighbourhood_group_cleansed' does contain useful information.
print(df_clean['neighbourhood_group_cleansed'].value_counts(dropna=False).head())

neighbourhood_group_cleansed
Mitte                       2826
Friedrichshain-Kreuzberg    2652
Pankow                      1950
Charlottenburg-Wilm.        1432
Neukölln                    1308
Name: count, dtype: int64

In [1192]:
#Column values are integer, there are no NA values, and there are no duplicates.
print(df["id"].dtype)
print(df["id"].isna().sum())
print(df["id"].duplicated().any())

int64
0
False

In [1193]:
#The listing_url column has a consistent format of https://www.airbnb.com/rooms/[id] where the [id] value is the same as the row id. Therefore, this column can be reconstructed with values already in the table and is redundant.
len(df[df["listing_url"] != "https://www.airbnb.com/rooms/" + df["id"].astype(str)])
df_clean = df_clean.drop("listing_url", axis=1) # move later

In [1194]:
#All rows contain the same value for scrape id, hence it can be removed. The values for this column imply that all data in the table came from the same scrape.
df_clean["scrape_id"].value_counts()
df_clean = df_clean.drop("scrape_id", axis=1) # move later

In [1195]:
#the data was scraped across 3 dates
df_clean["last_scraped"].value_counts()

last_scraped
2026-06-27    6624
2026-07-03    6118
2026-06-26      34
Name: count, dtype: int64

In [1196]:
#there were two seperate sources for the scrape, 'city' and 'previous'. The counts for each imply 'city' was scraped on 2026-06-27 and 2026-06-26 while 'previous' was scraped on 2026-07-03
df_clean["source"].value_counts()

source
city scrape        6658
previous scrape    6118
Name: count, dtype: int64

In [1197]:
#Name column has no apparent errors. Although it may be outside the scope of this project to explore name any deeper.
print(df_clean["name"].isna().sum())
print(df_clean["name"][df_clean["name"] == ""].sum())
df_clean = df_clean.drop("name", axis=1) # move later

0
0

In [1198]:
#559 listings have a missing description. The content of the description itself is also likey outside the scope of the exploration, however the presence (or lack) of a description could be relevant.
print(df_clean["description"].isna().sum())
print(df_clean["description"][df_clean["description"] == ""].sum())
print(df_clean["description"].head())
df_clean["description"] = df_clean["description"].isna() # move later

559
0
0    This beautiful first floor apartment  is situa...
1    4 bedroom with very large windows and outstand...
2    The apartment is located on the upper second f...
3    - bright studio with scenic view on a river - ...
4    Bright and sunny condo with two balconies in a...
Name: description, dtype: object

In [1199]:
#All listings have a relevant picture_url, however this column may not be relevant for use
print(df_clean['picture_url'].head())
print(df_clean['picture_url'].isna().sum())

0    https://a0.muscache.com/pictures/hosting/Hosti...
1    https://a0.muscache.com/pictures/42799131/59c8...
2    https://a0.muscache.com/pictures/hosting/Hosti...
3    https://a0.muscache.com/pictures/d9a6f8be-54b9...
4    https://a0.muscache.com/pictures/108232/205b19...
Name: picture_url, dtype: object
0

In [1200]:
#These columns will be useful for precise geographical data, and the columns themselves are clean.
print(df_clean[['latitude', 'longitude']].head())
print(df_clean['latitude'].isna().sum())
print(df_clean['longitude'].isna().sum())
print(df_clean['latitude'].dtype)
print(df_clean['longitude'].dtype)

   latitude  longitude
0  52.53574   13.41734
1  52.53269   13.41805
2  52.54624   13.40575
3  52.49626   13.42239
4  52.53711   13.40888
0
0
float64
float64

In [1201]:
night_cols = ['minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm']
print(df_clean[night_cols].head())

# minimum_nights is the same column as minimum_minimum_nights
print(str(len(
    df_clean[
    (df_clean['minimum_nights'] != df_clean['minimum_minimum_nights']) &
         df_clean['minimum_nights'].notna() &
         df_clean['minimum_minimum_nights'].notna()
    ])
) + " rows where minimum_nights and minimum_minimum_nights are not the same")

# maximum_nights is the same column as maximum_maximum_nights
print(str(len(
    df_clean[
    (df_clean['maximum_nights'] != df_clean['maximum_maximum_nights']) &
         df_clean['maximum_nights'].notna() &
         df_clean['maximum_maximum_nights'].notna()
    ])
) + " rows where maximum_nights and maximum_maximum_nights are not the same")

df_clean = df_clean.drop(['maximum_maximum_nights', 'minimum_minimum_nights'], axis=1) # move later

   minimum_nights  maximum_nights  minimum_minimum_nights  \
0             2.0           730.0                     2.0
1             6.0            14.0                     6.0
2           180.0          1125.0                   180.0
3            93.0           360.0                    93.0
4             3.0          1125.0                     3.0

   maximum_minimum_nights  minimum_maximum_nights  maximum_maximum_nights  \
0                    63.0                   730.0                   730.0
1                     6.0                    14.0                    14.0
2                   180.0                  1125.0                  1125.0
3                    93.0                   360.0                   360.0
4                     3.0                  1125.0                  1125.0

   minimum_nights_avg_ntm  maximum_nights_avg_ntm
0                    58.4                   730.0
1                     6.0                    14.0
2                   180.0                  1125.0
3                    93.0                   360.0
4                     3.0                  1125.0
0 rows where minimum_nights and minimum_minimum_nights are not the same
0 rows where maximum_nights and maximum_maximum_nights are not the same

In [1202]:
night_cols = ['minimum_nights', 'maximum_nights',
       'maximum_minimum_nights',
       'minimum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm']
df_clean[night_cols].isna().sum(axis=0)

minimum_nights            3
maximum_nights            3
maximum_minimum_nights    3
minimum_maximum_nights    3
minimum_nights_avg_ntm    0
maximum_nights_avg_ntm    0
dtype: int64

In [1203]:
df_clean.columns

Index(['id', 'last_scraped', 'source', 'description', 'picture_url', 'host_id',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'availability_eoy',
       'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'license'],
      dtype='object')

In [1204]:
cols = ['property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities']
df_clean[cols].head()

,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities
0,Entire rental unit,Entire home/apt,2,NaN,1 bath,1.0,NaN,"[""Oven"", ""Board games"", ""Baking sheet"", ""Cloth..."
1,Entire rental unit,Entire home/apt,7,2.5,2.5 baths,4.0,4.0,"[""Babysitter recommendations"", ""Elevator"", ""Hi..."
2,Entire rental unit,Entire home/apt,1,NaN,1 bath,NaN,NaN,"[""Oven"", ""Baking sheet"", ""Clothing storage"", ""..."
3,Entire rental unit,Entire home/apt,2,NaN,1 bath,NaN,NaN,"[""Free street parking"", ""Heating"", ""Long term ..."
4,Entire loft,Entire home/apt,4,1.0,1 bath,2.0,2.0,"[""Free washer \u2013 In unit"", ""Elevator"", ""Hi..."

In [1205]:
print(df_clean['property_type'].value_counts(dropna=False))
print(df_clean['room_type'].value_counts(dropna=False))

property_type
Entire rental unit             6990
Private room in rental unit    2503
Entire condo                    664
Entire serviced apartment       457
Room in hotel                   440
                               ...
Dome                              1
Shared room in condo              1
Private room in chalet            1
Shared room in home               1
Hut                               1
Name: count, Length: 62, dtype: int64
room_type
Entire home/apt    8846
Private room       3754
Hotel room           89
Shared room          87
Name: count, dtype: int64

In [1206]:
print(df_clean['bathrooms'].value_counts(dropna=False))
print(df_clean['bathrooms_text'].value_counts(dropna=False))
#RETURN BACK TO THIS, CAN CLEAN TEXT COLUMN TO GET RELEVANT MISSING VALUES FROM BATHROOMS COLUMN

bathrooms
NaN    6651
1.0    5005
2.0     535
1.5     362
0.5      69
3.0      61
2.5      55
4.0      22
3.5       6
8.5       4
4.5       3
5.0       1
8.0       1
6.0       1
Name: count, dtype: int64
bathrooms_text
1 bath               7721
1 shared bath        1802
1 private bath       1004
2 baths               862
1.5 baths             605
1.5 shared baths      164
2 shared baths        127
2.5 baths              94
0 baths                86
0 shared baths         64
3 baths                54
Shared half-bath       50
Half-bath              30
Private half-bath      24
3 shared baths         24
4 shared baths         16
2.5 shared baths       11
4 baths                 9
NaN                     8
3.5 baths               8
8.5 shared baths        3
4.5 baths               3
5 baths                 2
6 baths                 2
8 baths                 1
8.5 baths               1
8 shared baths          1
Name: count, dtype: int64

In [1207]:
print(df_clean['bedrooms'].value_counts(dropna=False))
print(df_clean['beds'].value_counts(dropna=False))

bedrooms
1.0     6103
NaN     3420
2.0     2219
3.0      775
4.0      182
5.0       47
6.0       17
0.0        4
7.0        3
9.0        2
8.0        2
14.0       1
12.0       1
Name: count, dtype: int64
beds
NaN     6254
1.0     2922
2.0     1673
3.0      843
4.0      505
5.0      201
6.0      169
8.0       73
7.0       67
9.0       25
10.0      16
11.0      13
12.0       7
14.0       3
13.0       2
15.0       2
50.0       1
Name: count, dtype: int64

In [1208]:
df_clean['amenities'].head()
#could probably pivot and clean these categories

0    ["Oven", "Board games", "Baking sheet", "Cloth...
1    ["Babysitter recommendations", "Elevator", "Hi...
2    ["Oven", "Baking sheet", "Clothing storage", "...
3    ["Free street parking", "Heating", "Long term ...
4    ["Free washer \u2013 In unit", "Elevator", "Hi...
Name: amenities, dtype: object

In [1209]:
price_cols = ['price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw']
df_clean[price_cols]

,price,price_quote_checkin_date,price_quote_checkout_date,price_quote_total_price,price_quote_price_per_night,price_quote_raw
0,$160.71,2026-07-25,2026-08-01,1125.0,160.71,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""..."
1,$193.33,2026-10-01,2026-10-07,1160.0,193.33,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""..."
2,NaN,2026-07-06,2027-01-02,NaN,NaN,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""..."
3,$10.88,2027-01-01,2027-04-04,1012.0,10.88,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""..."
4,$372.67,2026-06-29,2026-07-02,1118.0,372.67,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""..."
...,...,...,...,...,...,...
12771,$190.40,2026-06-30,2026-07-01,190.4,190.40,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""..."
12772,$201.80,2026-06-30,2026-07-01,201.8,201.80,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""..."
12773,$378.40,2026-07-31,2026-08-02,756.8,378.40,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""..."
12774,$188.80,2026-06-30,2026-07-01,188.8,188.80,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""..."
12775,$267.20,2026-07-02,2026-07-03,267.2,267.20,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""..."

In [1210]:
#all non-na values begin with "$" and numbers include commas. This column should be float
df_clean[df['price'].notna()]['price'].str[0].value_counts()
df_clean['price'] = df_clean['price'].str.replace("$", "").str.replace(",", "").astype(float)

In [1211]:
df_clean['price_quote_total_price'].dtype
df_clean['price_quote_price_per_night'].dtype

dtype('float64')

In [1212]:
availability_cols = ['has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'availability_eoy']
df_clean[availability_cols]

,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,availability_eoy
0,t,8,38,67,342,2026-07-03,159
1,t,6,15,18,261,2026-06-27,87
2,t,27,57,87,211,2026-07-03,179
3,t,0,0,0,184,2026-07-03,1
4,t,13,38,64,241,2026-06-27,159
...,...,...,...,...,...,...,...
12771,t,21,51,81,356,2026-06-27,179
12772,t,9,30,60,333,2026-06-27,156
12773,t,0,16,20,197,2026-06-27,20
12774,t,27,53,83,358,2026-06-27,181
12775,t,15,15,41,316,2026-06-27,139

In [1213]:
print(df_clean['has_availability'].value_counts(dropna=False))
df_clean['has_availability'] = df_clean['has_availability'].map({'t': True, 'f': False})
print(df_clean['has_availability'].value_counts(dropna=False))

has_availability
t      12559
NaN      165
f         52
Name: count, dtype: int64
has_availability
True     12559
NaN        165
False       52
Name: count, dtype: int64

In [1214]:
print(df_clean['availability_30'].dtype)
print(df_clean['availability_60'].dtype)
print(df_clean['availability_90'].dtype)
print(df_clean['availability_365'].dtype)
print(df_clean['availability_eoy'].dtype)

int64
int64
int64
int64
int64

In [1215]:
#the last_scraped and calendar_last_scraped columnas are identical, so we can drop the latter.
len(df_clean[df_clean['calendar_last_scraped'] != df_clean['last_scraped']])
df_clean = df_clean.drop('calendar_last_scraped', axis = 1)

In [1216]:
df_clean.columns

Index(['id', 'last_scraped', 'source', 'description', 'picture_url', 'host_id',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'availability_eoy', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'license'],
      dtype='object')

In [1217]:
remaining_cols = ['estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'license']

df_clean[remaining_cols]

,estimated_occupancy_l365d,estimated_revenue_l365d,license
0,13,2089.0,First name and Last name: Nicolas Krotz <br/> ...
1,0,0.0,03/Z/RA/003410-18
2,0,NaN,NaN
3,255,2774.0,NaN
4,76,28323.0,03/Z/RA/009767-24
...,...,...,...
12771,0,0.0,Legal entity name and Legal form: Arbio Akazia...
12772,0,0.0,Legal entity name and Legal form: Arbio Akazia...
12773,0,0.0,Legal entity name and Legal form: Arbio Akazia...
12774,0,0.0,Legal entity name and Legal form: Arbio Akazia...
12775,0,0.0,Legal entity name and Legal form: Arbio Akazia...

In [1218]:
df_clean[['host_id', 'license']]

         host_id                                            license
0           3718  First name and Last name: Nicolas Krotz <br/> ...
1          33852                                  03/Z/RA/003410-18
2          55531                                                NaN
3          68997                                                NaN
4          71331                                  03/Z/RA/009767-24
...          ...                                                ...
12771  177619318  Legal entity name and Legal form: Arbio Akazia...
12772  177619318  Legal entity name and Legal form: Arbio Akazia...
12773  177619318  Legal entity name and Legal form: Arbio Akazia...
12774  177619318  Legal entity name and Legal form: Arbio Akazia...
12775  177619318  Legal entity name and Legal form: Arbio Akazia...

[12776 rows x 2 columns]

In [1219]:
df_host['license'] = df_clean['license']
df_clean = df_clean.drop('license', axis=1)

In [1220]:
df_clean.columns

Index(['id', 'last_scraped', 'source', 'description', 'picture_url', 'host_id',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'availability_eoy', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d'],
      dtype='object')

#1.5 Transporting Clean Tables --------------

In [1222]:
df_host.to_csv("df_host_clean.csv", index=False)
df_clean.to_csv("df_listings_clean.csv", index=False)
df_review_statistics.to_csv("df_reviews_clean.csv", index=False)