In [30]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [31]:
import pandas as pd

file_path = '/content/drive/MyDrive/listings.csv'
df = pd.read_csv(file_path)
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3176,https://www.airbnb.com/rooms/3176,20260626225638,2026-07-03,previous scrape,Fabulous Flat in great Location,This beautiful first floor apartment is situa...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,3718,...,4.70,4.92,4.61,First name and Last name: Nicolas Krotz <br/> ...,NaN,1,1,0,0,0.72
1,9991,https://www.airbnb.com/rooms/9991,20260626225638,2026-06-27,city scrape,Geourgeous flat - outstanding views,4 bedroom with very large windows and outstand...,NaN,https://a0.muscache.com/pictures/42799131/59c8...,33852,...,5.00,4.86,4.86,03/Z/RA/003410-18,NaN,1,1,0,0,0.05
2,14325,https://www.airbnb.com/rooms/14325,20260626225638,2026-07-03,previous scrape,Studio Apartment in Prenzlauer Berg,The apartment is located on the upper second f...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,55531,...,4.85,4.60,4.45,NaN,NaN,2,2,0,0,0.13
3,17904,https://www.airbnb.com/rooms/17904,20260626225638,2026-07-03,previous scrape,Beautiful Kreuzberg studio - 3 months minimum,- bright studio with scenic view on a river - ...,NaN,https://a0.muscache.com/pictures/d9a6f8be-54b9...,68997,...,4.92,4.88,4.65,NaN,NaN,1,1,0,0,1.49
4,20858,https://www.airbnb.com/rooms/20858,20260626225638,2026-06-27,city scrape,Designer Loft in Berlin Mitte,Bright and sunny condo with two balconies in a...,NaN,https://a0.muscache.com/pictures/108232/205b19...,71331,...,4.55,4.92,4.40,03/Z/RA/009767-24,NaN,1,1,0,0,0.87

In [32]:
df.describe()

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,1.277600e+04,1.277600e+04,0.0,1.277600e+04,1.276000e+04,0.0,12760.000000,12760.000000,12760.000000,12760.000000,...,10201.000000,10203.000000,10201.000000,10201.000000,0.0,12776.000000,12776.000000,12776.000000,12776.000000,10203.000000
mean,6.144901e+17,2.026063e+13,NaN,3.696258e+15,1.471278e+18,NaN,8.222179,5.758777,6.454389,5.645925,...,4.832955,4.830695,4.768241,4.651415,NaN,14.433312,13.194427,1.034909,0.141124,1.340282
std,6.324319e+17,3.910309e+00,NaN,7.887474e+16,2.688485e+16,NaN,4.146422,3.519559,4.148220,3.482203,...,0.313080,0.341911,0.307369,0.393563,NaN,45.244762,45.219126,2.773292,1.527326,1.957176
min,3.176000e+03,2.026063e+13,NaN,2.217000e+03,1.462506e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,2.497952e+07,2.026063e+13,NaN,1.754369e+07,1.462887e+18,NaN,5.000000,3.000000,3.000000,3.000000,...,4.800000,4.800000,4.690000,4.540000,NaN,1.000000,0.000000,0.000000,0.000000,0.140000
50%,6.267416e+17,2.026063e+13,NaN,1.015032e+08,1.466838e+18,NaN,9.000000,6.000000,7.000000,6.000000,...,4.920000,4.930000,4.850000,4.730000,NaN,1.000000,1.000000,0.000000,0.000000,0.640000
75%,1.211491e+18,2.026063e+13,NaN,4.020121e+08,1.469768e+18,NaN,11.000000,9.000000,10.000000,9.000000,...,5.000000,5.000000,4.970000,4.880000,NaN,5.000000,3.000000,1.000000,0.000000,1.940000
max,1.715913e+18,2.026063e+13,NaN,1.711581e+18,1.714641e+18,NaN,17.000000,11.000000,15.000000,11.000000,...,5.000000,5.000000,5.000000,5.000000,NaN,261.000000,261.000000,25.000000,23.000000,45.120000

### There are too many columns in the dataset to explore within reason.
Therefore, I will explore the data and remove unusable or unecessary columns

In [33]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_profile_id', 'host_profile_url', 'host_name',
       'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [34]:
#There is host data present within the listings table that can be seperated into its own table.
host_cols = ['host_id',
       'host_url', 'host_profile_id', 'host_profile_url', 'host_name',
       'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms']
df_host = df[host_cols]

#This relationship from listings to hosts is many to one. The host data appears many times within the listings table, meaning it currently appears many times in the host table.
df_host = df_host.drop_duplicates()

#There are still duplicate ids in the table are removing duplicate rows
df_host["host_id"].value_counts()

host_id
560640615    2
695648086    2
198110578    2
706243170    2
689937375    2
            ..
113265170    1
150545454    1
1219287      1
75787504     1
23211273     1
Name: count, Length: 8182, dtype: int64

In [35]:
#It appears that remaining duplicate ids are due to host_profile_url being present in one instance but not the other.
duplicate_hosts = df_host["host_id"].value_counts()[df_host["host_id"].value_counts() > 1]
duplicate_ids = duplicate_hosts.index

df_host[df_host["host_id"].isin(duplicate_ids)].sort_values(by='host_id')

,host_id,host_url,host_profile_id,host_profile_url,host_name,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
5156,4011048,https://www.airbnb.com/users/show/4011048,1.462533e+18,https://www.airbnb.com/users/profile/146253307...,Yumi,NaN,13.0,8.0,6.0,0.0,...,NaN,3.0,NaN,NaN,t,t,3,1,2,0
5182,4011048,https://www.airbnb.com/users/show/4011048,1.462533e+18,NaN,Yumi,NaN,13.0,8.0,6.0,0.0,...,NaN,3.0,NaN,NaN,t,t,3,1,2,0
5834,198110578,https://www.airbnb.com/users/show/198110578,1.469032e+18,https://www.airbnb.com/users/profile/146903217...,Sarah,NaN,8.0,0.0,5.0,8.0,...,NaN,2.0,NaN,NaN,t,t,2,0,2,0
6554,198110578,https://www.airbnb.com/users/show/198110578,1.469032e+18,NaN,Sarah,NaN,8.0,0.0,5.0,8.0,...,NaN,2.0,NaN,NaN,t,t,2,0,2,0
8335,547505934,https://www.airbnb.com/users/show/547505934,1.470450e+18,NaN,Hotel AMO By AMANO,NaN,2.0,7.0,2.0,7.0,...,NaN,4.0,NaN,NaN,t,t,3,0,3,0
10952,547505934,https://www.airbnb.com/users/show/547505934,1.470450e+18,https://www.airbnb.com/users/profile/147044975...,Hotel AMO By AMANO,NaN,2.0,7.0,2.0,7.0,...,NaN,4.0,NaN,NaN,t,t,3,0,3,0
8793,560640615,https://www.airbnb.com/users/show/560640615,NaN,https://www.airbnb.com/users/profile/147050472...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,0
8791,560640615,https://www.airbnb.com/users/show/560640615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,0
10660,686441652,https://www.airbnb.com/users/show/686441652,NaN,https://www.airbnb.com/users/profile/147071346...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,0
10661,686441652,https://www.airbnb.com/users/show/686441652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,0
10742,689937375,https://www.airbnb.com/users/show/689937375,NaN,https://www.airbnb.com/users/profile/147072096...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0
10741,689937375,https://www.airbnb.com/users/show/689937375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0
10754,690328181,https://www.airbnb.com/users/show/690328181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4,0,4,0
10790,690328181,https://www.airbnb.com/users/show/690328181,NaN,https://www.airbnb.com/users/profile/147072185...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4,0,4,0
10886,695648086,https://www.airbnb.com/users/show/695648086,1.470733e+18,NaN,"Hotel Provocateur, Part Of Sircle Collection",NaN,1.0,1.0,1.0,1.0,...,NaN,8.0,NaN,NaN,t,t,5,0,5,0
10887,695648086,https://www.airbnb.com/users/show/695648086,1.470733e+18,https://www.airbnb.com/users/profile/147073306...,"Hotel Provocateur, Part Of Sircle Collection",NaN,1.0,1.0,1.0,1.0,...,NaN,8.0,NaN,NaN,t,t,5,0,5,0
11180,706243170,https://www.airbnb.com/users/show/706243170,1.470753e+18,https://www.airbnb.com/users/profile/147075310...,The Social Hub Berlin,NaN,0.0,11.0,0.0,11.0,...,NaN,8.0,NaN,NaN,t,t,7,0,7,0
11181,706243170,https://www.airbnb.com/users/show/706243170,1.470753e+18,NaN,The Social Hub Berlin,NaN,0.0,11.0,0.0,11.0,...,NaN,8.0,NaN,NaN,t,t,7,0,7,0
11640,723284548,https://www.airbnb.com/users/show/723284548,1.528833e+18,https://www.airbnb.com/users/profile/152883302...,B&B Hotel Berlin Alexanderplatz,NaN,0.0,8.0,0.0,8.0,...,NaN,5.0,NaN,NaN,t,t,2,0,2,0
12318,723284548,https://www.airbnb.com/users/show/723284548,1.528833e+18,NaN,B&B Hotel Berlin Alexanderplatz,NaN,0.0,8.0,0.0,8.0,...,NaN,5.0,NaN,NaN,t,t,2,0,2,0

In [36]:
#Since duplicate rows have are identical except for the profile url, we can drop the duplicate row without the profile url. This results in a table free of duplicate ids.
drop_idx = df_host[df_host["host_id"].isin(duplicate_ids) & df_host["host_profile_url"].isna()].index
df_host = df_host.drop(index = drop_idx)

len(df_host["host_id"].value_counts()[df_host["host_id"].value_counts() > 1])

0

In [37]:
#these columns are dropped from the listings table, but host_id is kept in order to maintain the relationship
df_clean = df.drop([col for col in host_cols if col != "host_id"], axis=1)
df_clean.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'reviews_per_month'],
      dtype='object')

In [38]:
review_statistics_cols = ['id', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
        'number_of_reviews_ly','first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'reviews_per_month']
df_review_statistics = df_clean[review_statistics_cols]
df_review_statistics.rename(columns={'id': 'listing_id'}, inplace=True)

#This relationship from listings to hosts is one to one. There should not be any duplicates in this table since it is one for each listing
df_review_statistics["listing_id"].value_counts()

/tmp/ipykernel_919/3804206786.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_review_statistics.rename(columns={'id': 'listing_id'}, inplace=True)

listing_id
1715912659116099298    1
3176                   1
9991                   1
14325                  1
17904                  1
                      ..
41217                  1
37836                  1
37004                  1
34854                  1
30295                  1
Name: count, Length: 12776, dtype: int64

In [39]:
df_review_statistics.head()

,listing_id,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,3176,150,1,0,2,2009-06-20,2025-08-09,4.63,4.67,4.52,4.65,4.70,4.92,4.61,0.72
1,9991,7,0,0,0,2015-08-09,2020-01-04,5.00,5.00,5.00,5.00,5.00,4.86,4.86,0.05
2,14325,26,0,0,0,2010-06-29,2023-11-30,4.68,5.00,4.85,4.70,4.85,4.60,4.45,0.13
3,17904,298,2,0,1,2010-02-18,2026-05-31,4.77,4.82,4.71,4.89,4.92,4.88,4.65,1.49
4,20858,145,6,1,4,2012-10-03,2026-05-29,4.49,4.61,4.65,4.51,4.55,4.92,4.40,0.87

In [40]:
df_clean = df_clean.drop([col for col in review_statistics_cols if col != "listing_id"], axis=1)
df_clean.columns

Index(['listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'availability_eoy', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'license', 'instant_bookable'],
      dtype='object')

In [63]:
#The "neighbourhood" column is useless; it contains only NA values. Whereas "neighbourhood_cleansed" is what the column should be.
print(df_clean["neighbourhood"].value_counts(dropna=False).head())
print(df_clean["neighbourhood_cleansed"].value_counts(dropna=False).head())
df_clean = df_clean.drop("neighbourhood", axis=1) # move later

neighbourhood
NaN    12776
Name: count, dtype: int64
neighbourhood_cleansed
Alexanderplatz              884
Frankfurter Allee Süd FK    675
Tempelhofer Vorstadt        568
Brunnenstr. Süd             514
Prenzlauer Berg Südwest     378
Name: count, dtype: int64

In [64]:
#The 'neighborhood_overview' column is also useless and contains no data. Whereas the 'neighbourhood_group_cleansed' does contain useful information.
print(df_clean['neighborhood_overview'].value_counts(dropna=False).head())
print(df_clean['neighbourhood_group_cleansed'].value_counts(dropna=False).head())
df_clean = df_clean.drop('neighborhood_overview', axis=1) # move later

neighborhood_overview
NaN    12776
Name: count, dtype: int64
neighbourhood_group_cleansed
Mitte                       2826
Friedrichshain-Kreuzberg    2652
Pankow                      1950
Charlottenburg-Wilm.        1432
Neukölln                    1308
Name: count, dtype: int64

In [41]:
#Column values are integer, there are no NA values, and there are no duplicates.
print(df["id"].dtype)
print(df["id"].isna().sum())
print(df["id"].duplicated().any())

int64
0
False

In [65]:
#The listing_url column has a consistent format of https://www.airbnb.com/rooms/[id] where the [id] value is the same as the row id. Therefore, this column can be reconstructed with values already in the table and is redundant.
len(df[df["listing_url"] != "https://www.airbnb.com/rooms/" + df["id"].astype(str)])
df_clean = df_clean.drop("listing_url", axis=1) # move later

In [67]:
#All rows contain the same value for scrape id, hence it can be removed. The values for this column imply that all data in the table came from the same scrape.
df_clean["scrape_id"].value_counts()
df_clean = df_clean.drop("scrape_id", axis=1) # move later

In [44]:
#the data was scraped across 3 dates
df_clean["last_scraped"].value_counts()

last_scraped
2026-06-27    6624
2026-07-03    6118
2026-06-26      34
Name: count, dtype: int64

In [45]:
#there were two seperate sources for the scrape, 'city' and 'previous'. The counts for each imply 'city' was scraped on 2026-06-27 and 2026-06-26 while 'previous' was scraped on 2026-07-03
df_clean["source"].value_counts()

source
city scrape        6658
previous scrape    6118
Name: count, dtype: int64

In [68]:
#Name column has no apparent errors. Although it may be outside the scope of this project to explore name any deeper.
print(df_clean["name"].isna().sum())
print(df_clean["name"][df_clean["name"] == ""].sum())
df_clean = df_clean.drop("name", axis=1) # move later

0
0

In [69]:
#559 listings have a missing description. The content of the description itself is also likey outside the scope of the exploration, however the presence (or lack) of a description could be relevant.
print(df_clean["description"].isna().sum())
print(df_clean["description"][df_clean["description"] == ""].sum())
print(df_clean["description"].head())
df_clean["description"] = df_clean["description"].isna() # move later

559
0
0    This beautiful first floor apartment  is situa...
1    4 bedroom with very large windows and outstand...
2    The apartment is located on the upper second f...
3    - bright studio with scenic view on a river - ...
4    Bright and sunny condo with two balconies in a...
Name: description, dtype: object

In [72]:
#All listings have a relevant picture_url, however this column may not be relevant for use
print(df_clean['picture_url'].head())
print(df_clean['picture_url'].isna().sum())

0    https://a0.muscache.com/pictures/hosting/Hosti...
1    https://a0.muscache.com/pictures/42799131/59c8...
2    https://a0.muscache.com/pictures/hosting/Hosti...
3    https://a0.muscache.com/pictures/d9a6f8be-54b9...
4    https://a0.muscache.com/pictures/108232/205b19...
Name: picture_url, dtype: object
0

In [78]:
#These columns will be useful for precise geographical data, and the columns themselves are clean.
print(df_clean[['latitude', 'longitude']].head())
print(df_clean['latitude'].isna().sum())
print(df_clean['longitude'].isna().sum())
print(df_clean['latitude'].dtype)
print(df_clean['longitude'].dtype)

   latitude  longitude
0  52.53574   13.41734
1  52.53269   13.41805
2  52.54624   13.40575
3  52.49626   13.42239
4  52.53711   13.40888
0
0
float64
float64

In [82]:
night_cols = ['minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm']
df_clean[night_cols].head()

# minimum_nights is the same column as minimum_minimum_nights
df_clean[df_clean['minimum_nights'] != df_clean['minimum_minimum_nights'] & df_clean['minimum_nights']][night_cols]

,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm
697,NaN,NaN,NaN,NaN,NaN,NaN,92.0,95.0
2261,NaN,NaN,NaN,NaN,NaN,NaN,100.0,200.0
12186,NaN,NaN,NaN,NaN,NaN,NaN,4.2,200.0